import type { UpstreamAccountsPageCopy } from "@/lib/upstream-accounts-page-copy-types";

export const upstreamAccountsPageCopyEn: UpstreamAccountsPageCopy = {
  intake: {
    eyebrow: "OAuth intake",
    title: "Bring Codex upstream identities into the tenant pool.",
    description:
      "Generate an OpenAI OAuth authorization link first, then finalize the account after you have the callback code and state. This mirrors the sub2api operator flow.",
    tabs: { start: "1. Generate auth link", complete: "2. Complete account intake" },
    selectTenant: "Select a tenant",
    start: {
      labels: {
        tenant: "Tenant",
        selectTenant: "Select a tenant",
        redirectUri: "Redirect URI",
        proxyUrl: "Proxy URL",
        authUrl: "Authorization link",
        expiresAt: "Expires at",
        sessionId: "session_id",
        state: "state",
      },
      hints: {
        redirectUri: "Leave blank to use the backend default callback URI",
        proxyUrl: "Optional, for environments that need a proxy to reach OpenAI OAuth",
      },
      actions: { generate: "Generate auth link", open: "Open auth link" },
      messages: { generated: "Authorization link created." },
    },
    complete: {
      labels: {
        tenant: "Tenant",
        selectTenant: "Select a tenant",
        sessionId: "Session ID",
        state: "State",
        code: "Authorization code",
        name: "Account name",
        status: "Status",
      },
      hints: {
        code: "Paste the callback code from the browser here",
        state: "Use the state returned from step one",
        sessionId: "Use the session_id returned from step one",
      },
      actions: { create: "Complete intake" },
      status: { active: "Active", disabled: "Disabled" },
      messages: { created: "Upstream account connected." },
    },
  },
  table: {
    eyebrow: "Upstream pool",
    title: "Operate real Codex identities as schedulable inventory.",
    description:
      "This page exposes the OpenAI OAuth upstream accounts behind each tenant, including priority, cooldown state, recency, and last error so the pool behaves like sub2api rather than a blind proxy.",
    empty: "No upstream accounts connected yet.",
    noteTitle: "Scheduler note",
    noteBody:
      "The gateway now prefers lower priority accounts and skips identities that are cooling down or already expired. The table reflects the same live scheduler metadata the backend is using.",
    labels: {
      tenant: "Tenant",
      status: "Status",
      priority: "Priority",
      lastUsed: "Last used",
      cooldown: "Cooldown until",
      lastError: "Last error",
      refresh: "Refresh",
      email: "Email",
      failures: "Failures",
      never: "Never",
      clear: "Clear",
      hasRefreshToken: "Has refresh token",
      noRefreshToken: "No refresh token",
    },
  },
  summary: {
    totalAccounts: "Total accounts",
    inTenantPool: "In the tenant pool",
    active: "Active",
    eligibleForRouting: "Eligible for routing",
    cooling: "Cooling",
    temporarilyRemoved: "Temporarily removed",
    disabled: "Disabled",
    manuallyStopped: "Manually stopped",
    expiringSoon: "Expiring soon",
    tokenNeedsRefresh: "Token needs refresh within 24h",
    topErrors: "Top errors (current page)",
    noRecentErrors: "No recent errors on this page.",
    topTenants: "Top tenants (current page)",
    noTenantDistribution: "No tenant distribution yet.",
  },
  dialogs: {
    details: "Details",
    detailsTitle: "Upstream Account Details",
    detailsDescription: (name) => `View full metadata and scheduling state for ${name}.`,
    edit: "Edit",
    save: "Save Changes",
    cancel: "Cancel",
    editTitle: "Edit Upstream Account",
    editDescription: "Adjust scheduling priority, status, and time windows for account pool management.",
    refresh: "Refresh",
    runRefresh: "Refresh Token Now",
    refreshTitle: "Refresh Upstream Account",
    refreshDescription: (name) => `Attempt to fetch a new access token for ${name}.`,
    delete: "Delete",
    confirmDelete: "Confirm Delete",
    deleteTitle: "Delete Upstream Account",
    deleteDescription: (name) => `This will remove ${name} from the tenant account pool.`,
    fields: {
      id: "ID",
      name: "Name",
      tenantId: "Tenant ID",
      accountType: "Account Type",
      platform: "Platform",
      status: "Status",
      priority: "Priority",
      consecutiveFailures: "Consecutive Failures",
      lastUsedAt: "Last Used At",
      cooldownUntil: "Cooldown Until",
      createdAt: "Created At",
      updatedAt: "Updated At",
      extra: "Extra",
    },
  },
  actions: {
    oauthLinkCreated: "OAuth authorization link created successfully.",
    accountConnected: "Upstream account connected successfully.",
    accountUpdated: "Upstream account updated successfully.",
    accountDeleted: "Upstream account deleted successfully.",
    accountRefreshed: "Upstream account refreshed successfully.",
  },
};
