import type { UpstreamAccountsPageCopy } from "@/lib/upstream-accounts-page-copy-types";

export const upstreamAccountsPageCopyZh: UpstreamAccountsPageCopy = {
  intake: {
    eyebrow: "OAuth 接入台",
    title: "把 Codex 上游账号纳入租户账号池。",
    description:
      "先生成 OpenAI OAuth 授权链接，再在拿到 code 和 state 后完成账号落库。这个流程贴近 sub2api 的后台接入方式。",
    tabs: { start: "1. 生成授权链接", complete: "2. 完成账号接入" },
    selectTenant: "选择租户",
    start: {
      labels: {
        tenant: "租户",
        selectTenant: "选择租户",
        redirectUri: "回调地址",
        proxyUrl: "代理地址",
        authUrl: "授权链接",
        expiresAt: "过期时间",
        sessionId: "session_id",
        state: "state",
      },
      hints: {
        redirectUri: "留空则使用后端默认回调地址",
        proxyUrl: "可选，用于需要代理访问 OpenAI OAuth 的场景",
      },
      actions: { generate: "生成授权链接", open: "打开授权链接" },
      messages: { generated: "授权链接已生成。" },
    },
    complete: {
      labels: {
        tenant: "租户",
        selectTenant: "选择租户",
        sessionId: "Session ID",
        state: "State",
        code: "授权码",
        name: "账号名称",
        status: "状态",
      },
      hints: {
        code: "把浏览器回调中的 code 粘贴到这里",
        state: "使用第一步生成的 state",
        sessionId: "使用第一步返回的 session_id",
      },
      actions: { create: "完成接入" },
      status: { active: "活跃", disabled: "禁用" },
      messages: { created: "上游账号已接入。" },
    },
  },
  table: {
    eyebrow: "上游账号池",
    title: "把真实 Codex 身份当作可调度资源来运营。",
    description:
      "这里展示租户名下的 OpenAI OAuth 上游账号，以及优先级、冷却状态、最近使用时间和最近错误，方便你按 sub2api 的方式管理账号池。",
    empty: "当前还没有接入任何上游账号。",
    noteTitle: "调度说明",
    noteBody:
      "网关现在会优先选择更低的 priority，并避开冷却中或已过期的账号。这里的字段就是调度层正在使用的真实状态。",
    labels: {
      tenant: "租户",
      status: "状态",
      priority: "优先级",
      lastUsed: "最近使用",
      cooldown: "冷却至",
      lastError: "最近错误",
      refresh: "刷新",
      email: "邮箱",
      failures: "失败次数",
      never: "从未",
      clear: "无",
      hasRefreshToken: "有 refresh token",
      noRefreshToken: "无 refresh token",
    },
  },
  summary: {
    totalAccounts: "账号总数",
    inTenantPool: "租户池内记录数",
    active: "活跃",
    eligibleForRouting: "可参与路由调度",
    cooling: "冷却中",
    temporarilyRemoved: "暂时摘除等待恢复",
    disabled: "禁用",
    manuallyStopped: "手动停止",
    expiringSoon: "即将过期",
    tokenNeedsRefresh: "24 小时内需要刷新 token",
    topErrors: "高频错误（当前页）",
    noRecentErrors: "当前页暂无错误记录。",
    topTenants: "租户视角（当前页）",
    noTenantDistribution: "当前页暂无租户分布。",
  },
  dialogs: {
    details: "详情",
    detailsTitle: "上游账号详情",
    detailsDescription: (name) => `查看 ${name} 的完整元数据和调度状态。`,
    edit: "编辑",
    save: "保存修改",
    cancel: "取消",
    editTitle: "编辑上游账号",
    editDescription: "调整调度优先级、状态和时间窗口，方便运营处理账号池。",
    refresh: "刷新",
    runRefresh: "立即刷新 Token",
    refreshTitle: "刷新上游账号",
    refreshDescription: (name) => `尝试为 ${name} 拉取新的 access token。`,
    delete: "删除",
    confirmDelete: "确认删除",
    deleteTitle: "删除上游账号",
    deleteDescription: (name) => `删除后将把 ${name} 从租户账号池中移除。`,
    fields: {
      id: "ID",
      name: "名称",
      tenantId: "租户 ID",
      accountType: "账号类型",
      platform: "平台",
      status: "状态",
      priority: "优先级",
      consecutiveFailures: "连续失败次数",
      lastUsedAt: "最近使用时间",
      cooldownUntil: "冷却到期时间",
      createdAt: "创建时间",
      updatedAt: "更新时间",
      extra: "扩展信息",
    },
  },
  actions: {
    oauthLinkCreated: "OAuth 授权链接已创建。",
    accountConnected: "上游账号已接入。",
    accountUpdated: "上游账号已更新。",
    accountDeleted: "上游账号已删除。",
    accountRefreshed: "上游账号已刷新。",
  },
};
