import type { Locale } from "@/lib/i18n";
import type { WalletPageCopy } from "@/lib/wallet-page-copy-types";

const copy: Record<Locale, WalletPageCopy> = {
  en: {
    header: { title: "Account Funding", subtitle: "Multiple funding methods, safe and convenient", billing: "Billing" },
    stats: { accountStats: "Account Stats", currentBalance: "Current Balance", historicalSpend: "Historical Spend", requestCount: "Request Count" },
    recharge: {
      quickHint: "Quick funding tip",
      exchangeRate: "(1 $ = 6.80 CNY)",
      vipHint: "Funding and enterprise WeChat: LHSSOS",
      paidAmount: (amount) => `Paid ${amount}`,
      savedAmount: "Saved ¥0.00",
      redeemTitle: "Redeem Code Funding",
      redeemPlaceholder: "Enter redeem code",
      redeemAction: "Redeem Credit",
    },
    purchase: {
      title: "Create Plan Order",
      creditAmount: (amount, quota) => `Credit ¥${amount} / Quota ${quota}`,
      notePlaceholder: "Note, e.g. auto-buy Growth 680",
      submitting: "Creating...",
      submit: "Create Plan Order",
    },
    catalog: {
      chooseChannel: "Choose payment channel",
      subscriptionTitle: "Subscription Plans",
      subscriptionSubtitle: "Buy plans for model quota and request capacity",
      subscriptionAction: "Priority Subscribe",
      emptyPlans: "No plans available yet",
      featuredPlanFallback: "A stable top-up plan for a multi-tenant AI gateway.",
      planCreditSummary: (amount, quota) => `Credit ¥${amount} / Quota ${quota}`,
      createPlan: "New Plan",
      createChannel: "New Channel",
    },
    affiliate: {
      title: "Platform Growth Program",
      subtitle: "Invite friends and keep earning usage commission",
      commissionStats: "Commission Stats",
      withdraw: "Withdraw",
      transferToBalance: "Transfer to Balance",
      totalRecharged: "Total Recharged",
      successfulRequests: "Successful Requests",
      failedRequests: "Failed Requests",
      inviteLink: "Invite Link",
      copy: "Copy",
      commissionNotes: "Commission Notes",
      notes: [
        "After your invite registers, you earn 2.5% commission on each of their payments.",
        "Commission can be withdrawn or transferred into balance for usage.",
        "The more friends you invite, the higher the recurring revenue.",
      ],
      kolTitle: "KOL Partnership",
      kolDescription: "Apply to become a KOL and unlock a higher commission rate.",
      applyKol: "Apply as KOL",
    },
    orders: {
      createOrder: "Create Funding Order",
      amountPlaceholder: "Order amount, e.g. 68",
      creditedAmountPlaceholder: "Credited amount, optional",
      providerPlaceholder: "Payment provider, e.g. alipay",
      channelPlaceholder: "Payment channel, e.g. qrcode",
      notePlaceholder: "Note, e.g. manual recharge fix",
      submitting: "Submitting...",
      submit: "Create Funding Order",
      recentOrders: "Recent Orders",
      emptyOrders: "No funding orders yet",
      manualProvider: "manual",
      settling: "Crediting...",
      settle: "Manual Credit",
      updateNotePlaceholder: "Update note, e.g. waiting callback",
      updating: "Updating...",
      update: "Update Order",
      delete: "Delete",
    },
    history: {
      title: "Recent Ledger Entries",
      empty: "No ledger changes yet",
      balanceMeta: (direction, amount) => `${direction} / Balance ${amount}`,
    },
    forms: {
      newPlanTitle: "New Plan",
      newPlanBadgePlaceholder: "Recommended",
      newPlanDescriptionPlaceholder: "Good for steady traffic and team sharing",
      newPlanFeatured: "Mark as featured plan",
      newPlanSubmitting: "Submitting...",
      newPlanSubmit: "Create Plan",
      newChannelTitle: "New Payment Channel",
      newChannelNamePlaceholder: "Alipay (Recommended)",
      newChannelDescriptionPlaceholder: "Fast domestic collection, ideal for daily funding",
      newChannelRecommended: "Mark as recommended channel",
      newChannelSubmitting: "Submitting...",
      newChannelSubmit: "Create Channel",
      edit: "Edit",
      remove: "Delete",
      cancel: "Cancel",
      save: "Save Changes",
      saving: "Saving...",
      deleting: "Deleting...",
      confirmDelete: "Confirm Delete",
      planEditTitle: "Edit Plan",
      planEditDescription: "Adjust price, quota, sort order, and badge display.",
      planDeleteTitle: "Delete Plan",
      planDeleteDescription: (name) => `Deleting will remove plan "${name}" from the console.`,
      channelEditTitle: "Edit Payment Channel",
      channelEditDescription: "Adjust provider, channel code, sort order, and recommendation status.",
      channelDeleteTitle: "Delete Payment Channel",
      channelDeleteDescription: (name) => `Deleting will remove the funding entry for "${name}".`,
      featuredBadge: "Featured",
      recommendedBadge: "Recommended",
      statusActive: "active",
      statusDisabled: "disabled",
    },
  },
  "zh-CN": {
    header: { title: "账户充值", subtitle: "多种充值方式，安全便捷", billing: "账单" },
    stats: { accountStats: "账户统计", currentBalance: "当前余额", historicalSpend: "历史消耗", requestCount: "请求次数" },
    recharge: {
      quickHint: "快速充值提示",
      exchangeRate: "(1 $ = 6.80 ￥)",
      vipHint: "充值以及大客户经理微信: LHSSOS",
      paidAmount: (amount) => `实付 ${amount}`,
      savedAmount: "节省 ¥0.00",
      redeemTitle: "兑换码充值",
      redeemPlaceholder: "请输入兑换码",
      redeemAction: "兑换额度",
    },
    purchase: {
      title: "按套餐下单",
      creditAmount: (amount, quota) => `入账 ¥${amount} / 额度 ${quota}`,
      notePlaceholder: "备注，例如自动购买 Growth 680",
      submitting: "创建中...",
      submit: "创建套餐订单",
    },
    catalog: {
      chooseChannel: "选择支付方式",
      subscriptionTitle: "订阅套餐",
      subscriptionSubtitle: "购买订阅获得模型额度/次数",
      subscriptionAction: "优先订阅",
      emptyPlans: "暂无可购买套餐",
      featuredPlanFallback: "适合多租户 AI 中转站的稳定充值方案。",
      planCreditSummary: (amount, quota) => `入账 ¥${amount} / 额度 ${quota}`,
      createPlan: "新增套餐",
      createChannel: "新增支付渠道",
    },
    affiliate: {
      title: "平台成长计划",
      subtitle: "邀请好友，持续获得消费佣金",
      commissionStats: "佣金统计",
      withdraw: "提现",
      transferToBalance: "划转到余额",
      totalRecharged: "累计充值",
      successfulRequests: "成功请求",
      failedRequests: "失败请求",
      inviteLink: "邀请链接",
      copy: "复制",
      commissionNotes: "佣金说明",
      notes: [
        "邀请好友注册后，好友每次消费您都将获得 2.5% 的佣金",
        "佣金可申请提现或划转到账户余额使用",
        "邀请的好友越多，持续收益越高",
      ],
      kolTitle: "KOL 合作",
      kolDescription: "申请成为 KOL，获得更高返佣比例",
      applyKol: "申请成为 KOL",
    },
    orders: {
      createOrder: "创建充值单",
      amountPlaceholder: "订单金额，例如 68",
      creditedAmountPlaceholder: "入账金额，可留空",
      providerPlaceholder: "支付提供方，例如 alipay",
      channelPlaceholder: "支付渠道，例如 qrcode",
      notePlaceholder: "备注，例如人工补单",
      submitting: "提交中...",
      submit: "创建充值单",
      recentOrders: "最近充值单",
      emptyOrders: "暂无充值订单",
      manualProvider: "manual",
      settling: "入账中...",
      settle: "手动入账",
      updateNotePlaceholder: "更新备注，例如等待回调",
      updating: "更新中...",
      update: "更新订单",
      delete: "删除",
    },
    history: {
      title: "最近账本记录",
      empty: "暂无账本变动",
      balanceMeta: (direction, amount) => `${direction} / 余额 ${amount}`,
    },
    forms: {
      newPlanTitle: "新增套餐",
      newPlanBadgePlaceholder: "推荐",
      newPlanDescriptionPlaceholder: "适合稳定流量与团队共享",
      newPlanFeatured: "设为推荐套餐",
      newPlanSubmitting: "提交中...",
      newPlanSubmit: "创建套餐",
      newChannelTitle: "新增支付渠道",
      newChannelNamePlaceholder: "支付宝(推荐)",
      newChannelDescriptionPlaceholder: "国内收款响应快，适合日常充值",
      newChannelRecommended: "设为推荐渠道",
      newChannelSubmitting: "提交中...",
      newChannelSubmit: "创建渠道",
      edit: "编辑",
      remove: "删除",
      cancel: "取消",
      save: "保存修改",
      saving: "保存中...",
      deleting: "删除中...",
      confirmDelete: "确认删除",
      planEditTitle: "编辑套餐",
      planEditDescription: "调整价格、额度、排序与展示标签。",
      planDeleteTitle: "删除套餐",
      planDeleteDescription: (name) => `删除后将移除套餐 “${name}” 的控制台展示。`,
      channelEditTitle: "编辑支付渠道",
      channelEditDescription: "调整 provider、渠道编码、排序和推荐状态。",
      channelDeleteTitle: "删除支付渠道",
      channelDeleteDescription: (name) => `删除后将移除渠道 “${name}” 的充值入口。`,
      featuredBadge: "推荐",
      recommendedBadge: "推荐",
      statusActive: "active",
      statusDisabled: "disabled",
    },
  },
};

export function getWalletPageCopy(locale: Locale) {
  return copy[locale];
}
